import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import NavBar from "../components/nav_bar/nav_bar";
import Footer from "../components/footer/footer";
import {
  workContents,
  toolListContents,
  skillContents,
  achieveContents,
  projectContents,
} from "../contents/config";
import { Inter } from "next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const displayToolList = toolListContents.map((tool, i) => {
    return (
      <li key={i}>
        <Image
          src={`/tools/${tool}.svg`}
          fill
          style={{ objectFit: "contain" }}
          alt={`${tool}_logo`}
        />
      </li>
    );
  });

  const displayWorkList = workContents.map(
    ({ jobTitle, company, period }, i) => (
      <li key={i}>
        <h3>{jobTitle}</h3>
        <h4>{company}</h4>
        <p>{period}</p>
      </li>
    )
  );

  const displaySkillList = skillContents.map(({ icon, title, process }, i) => (
    <li key={i}>
      <div>
        <Image src={icon} width={24} height={24} alt="" />
        <h3>{title}</h3>
      </div>
      <div className={styles.process_img}>
        <Image
          src={process}
          fill
          style={{ objectFit: "contain", objectPosition: "left" }}
          alt=""
        />
      </div>
    </li>
  ));

  const displayAchievements = achieveContents.map(
    ({ image, title, subTitle }, i) => {
      const imageSize = i === 0 ? 130 : 150;
      return (
        <li key={i}>
          <div>
            <Image src={image} width={imageSize} height={imageSize} alt="" />
          </div>
          <h2>{title}</h2>
          <p>{subTitle}</p>
        </li>
      );
    }
  );

  const displayProjects = projectContents.map(
    ({ title, description, image, link }, i) => (
      <div key={i} className={styles.project_block}>
        <div className={styles.project_text}>
          <h2>{title}</h2>
          <p>{description}</p>
          <Link href={link}>
            <button>
              {/* Star icon */}
              <div></div>
              <p>Learn More</p>
            </button>
          </Link>
        </div>
        <div className={styles.project_image}>
          <Image src={image} fill style={{ objectFit: "contain" }} alt="" />
        </div>
      </div>
    )
  );

  const getIllustrationList = (quantity: number) => {
    const listArr = Array.from({ length: quantity }, (_, i) => i + 1);

    const illustrationList = listArr.map((v) => {
      const imgSrc = v < 10 ? `0${v}` : `${v}`;
      return (
        <li key={v}>
          <Image
            src={`/illustrations/${imgSrc}.png`}
            width={300}
            height={300}
            alt=""
          />
        </li>
      );
    });

    return illustrationList;
  };

  return (
    <>
      <Head>
        <title>Jodie Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <main className={`${styles.super_container} ${inter.className}`}>
        {/* 簡介 */}
        <div className={styles.main_container}>
          <div className={styles.description}>
            <p>Hello world !</p>
            <h1>
              Hi ! I am Jodie <br /> UIUX Designer
            </h1>
            <h2>
              I create better experiences for <b>users</b>
              <span>People</span>
            </h2>

            <ul className={styles.tool_list}>{displayToolList}</ul>
          </div>

          <div className={styles.picture_container}>
            <Image
              src="/tools/My_picture.png"
              fill
              style={{ objectFit: "cover" }}
              alt="Jodie's_picture"
            />
          </div>
        </div>

        {/* History */}
        <div className={styles.history_container}>
          {/* 從照片接下來的線 */}
          <div className={styles.orangeLine}>
            <span></span>
          </div>
          <div className={styles.history_list}>
            <div className={styles.work_container}>
              <h2>WORK EXPERIENCE</h2>
              <ul>{displayWorkList}</ul>
            </div>
            <div className={styles.skill_container}>
              <h2>SKILL AND EXPERTISE</h2>
              <ul>{displaySkillList}</ul>
            </div>
          </div>
        </div>

        {/* Achievements */}
        <div className={styles.achieve_container}>
          <ul>{displayAchievements}</ul>
        </div>

        {/* Projects */}
        <div className={styles.project_container}>{displayProjects}</div>

        {/* Illustrations */}
        <div className={styles.illustration_container}>
          <p>ILLUSTRATIONS</p>
          <h2>What’s in my imagination</h2>
          <div className={styles.illustration_list}>
            <ul>{getIllustrationList(4)}</ul>
          </div>
          <Link href={"/"}>
            <button>
              <Image src={"/icons/play.svg"} width={44} height={44} alt="" />
              <p>See More</p>
            </button>
          </Link>
        </div>
      </main>

      <Footer />
    </>
  );
}
