import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import NavBar from "../components/nav_bar/nav_bar";
import Footer from "../components/footer/footer";
import { Inter } from "next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

const toolListContents = ["Figma", "XD", "AI", "AE", "PS", "Procreate"];
const workCotents = [
  {
    jobTitle: "Senior UI/UX Designer",
    company: "iSunCloud-Taiwan",
    period: "2022 - Present",
  },
  {
    jobTitle: "UI/UX Designer",
    company: "MerMer Inc.",
    period: "2020 - 2022",
  },
  {
    jobTitle: "Art Director",
    company: "Penetration Internet Agency",
    period: "2018 - 2020",
  },
  {
    jobTitle: "Graphic Designer",
    company: "Freelancer",
    period: "2014 - 2018",
  },
];
const skillContents = [
  {
    icon: "/icons/design.svg",
    title: "UIUX Design",
    process: "/process/uiux_progress.svg",
  },
  {
    icon: "/icons/global.svg",
    title: "User Research",
    process: "/process/user_progress.svg",
  },
  {
    icon: "/icons/basketBall.svg",
    title: "Logo Design",
    process: "/process/logo_progress.svg",
  },
  {
    icon: "/icons/camera.svg",
    title: "Graphic Illustrations",
    process: "/process/graphic_progress.svg",
  },
  {
    icon: "/icons/asterisk.svg",
    title: "Animation",
    process: "/process/animation_progress.svg",
  },
];
const achieveContents = [
  {
    image: "/icons/projects.png",
    title: "28",
    subTitle: "Completed Projects",
  },
  {
    image: "/icons/hours.png",
    title: "16640",
    subTitle: "Working Hours",
  },
  {
    image: "/icons/clients.png",
    title: "48",
    subTitle: "Happy Clients",
  },
];
const projectContents = [
  {
    title: "TideBit-Defi",
    description:
      "TideBit-Defi is a crypto exchange platform that focus on decentralized financial trading.",
    image: "/projects/TideBit_Mockup.png",
    link: "/",
  },
  {
    title: "BAIFA",
    description:
      "BAIFA (BOLT AI Forensic Accounting and AuditingI ) is like google in blockchain’s world. You can search information that has been uploaded to the blockchains here. Further more, BOLT-Explorer offers tool for user to trace transactions, audit data, check on black list to reduce the crimes.",
    image: "/projects/Bolt.png",
    link: "/",
  },
  {
    title: "BOLT-Mining Software",
    description:
      "BOLT-Mining Software allows the user to mine crypto in an easier and interesting way.",
    image: "/projects/Mining.png",
    link: "/",
  },
  {
    title: "Other Web Design",
    description: "I also created a lot of official websites for businesses.",
    image: "/projects/Web.png",
    link: "/",
  },
];

export default function Home() {
  const displayToolList = toolListContents.map((tool, i) => {
    return (
      <li key={i}>
        <Image
          src={`/tools/${tool}.svg`}
          fill
          style={{ objectFit: "contain" }}
          alt={`${tool}_logo`}
        />
      </li>
    );
  });

  const displayWorkList = workCotents.map(
    ({ jobTitle, company, period }, i) => (
      <li key={i}>
        <h3>{jobTitle}</h3>
        <h4>{company}</h4>
        <p>{period}</p>
      </li>
    )
  );

  const displaySkillList = skillContents.map(({ icon, title, process }, i) => (
    <li key={i}>
      <div>
        <Image src={icon} width={24} height={24} alt="" />
        <h3>{title}</h3>
      </div>
      <div className={styles.process_img}>
        <Image
          src={process}
          fill
          style={{ objectFit: "contain", objectPosition: "left" }}
          alt=""
        />
      </div>
    </li>
  ));

  const displayAchievements = achieveContents.map(
    ({ image, title, subTitle }, i) => {
      const imageSize = i === 0 ? 130 : 150;
      return (
        <li key={i}>
          <div>
            <Image src={image} width={imageSize} height={imageSize} alt="" />
          </div>
          <h2>{title}</h2>
          <p>{subTitle}</p>
        </li>
      );
    }
  );

  const displayProjects = projectContents.map(
    ({ title, description, image, link }, i) => (
      <div key={i} className={styles.project_block}>
        <div className={styles.project_text}>
          <h2>{title}</h2>
          <p>{description}</p>
          <Link href={link}>
            <button>
              {/* Star icon */}
              <div></div>
              <p>Learn More</p>
            </button>
          </Link>
        </div>
        <div className={styles.project_image}>
          <Image src={image} fill style={{ objectFit: "contain" }} alt="" />
        </div>
      </div>
    )
  );

  return (
    <>
      <Head>
        <title>Jodie Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <main className={`${styles.super_container} ${inter.className}`}>
        {/* 簡介 */}
        <div className={styles.main_container}>
          <div className={styles.description}>
            <p>Hello world !</p>
            <h1>
              Hi ! I am Jodie <br /> UIUX Designer
            </h1>
            <h2>
              I create better experiences for <b>users</b>
              <span>People</span>
            </h2>

            <ul className={styles.tool_list}>{displayToolList}</ul>
          </div>

          <div className={styles.picture_container}>
            <Image
              src="/tools/My_picture.png"
              fill
              style={{ objectFit: "cover" }}
              alt="Jodie's_picture"
            />
          </div>
        </div>

        {/* History */}
        <div className={styles.history_container}>
          {/* 從照片接下來的線 */}
          <div className={styles.orangeLine}>
            <span></span>
          </div>
          <div className={styles.history_list}>
            <div className={styles.work_container}>
              <h2>WORK EXPERIENCE</h2>
              <ul>{displayWorkList}</ul>
            </div>
            <div className={styles.skill_container}>
              <h2>SKILL AND EXPERTISE</h2>
              <ul>{displaySkillList}</ul>
            </div>
          </div>
        </div>

        {/* Achievements */}
        <div className={styles.achieve_container}>
          <ul>{displayAchievements}</ul>
        </div>

        {/* Projects */}
        <div className={styles.project_container}>{displayProjects}</div>

        {/* Illustrations */}
        <div className={styles.illustration_container}>
          <p>illustrations</p>
          <h2>What’s in my imagination</h2>
          <div className={styles.illustration_list}></div>
        </div>
      </main>

      <Footer />
    </>
  );
}
